#!/usr/bin/env bash
# setup-offline.sh — ZeroClaw fully offline, zero-cost auto-setup
#
# Copy-paste and run:
#   bash scripts/setup-offline.sh
#
# What this does:
#   1. Installs the zeroclaw binary if not already present
#   2. Installs Ollama if not already present
#   3. Pulls a capable local model
#   4. Creates ~/.zeroclaw/ config directory
#   5. Writes an offline-optimised config.toml
#   6. Runs a smoke test to confirm end-to-end works

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
    BOLD='\033[1m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'
    YELLOW='\033[1;33m'; RESET='\033[0m'
else
    BOLD=''; GREEN=''; CYAN=''; YELLOW=''; RESET=''
fi

info()    { echo -e "${GREEN}[setup]${RESET} $*"; }
section() { echo -e "\n${BOLD}${CYAN}━━  $*  ━━${RESET}"; }
note()    { echo -e "${YELLOW}[note]${RESET}  $*"; }

# ── Default model (override with MODEL=phi4 bash setup-offline.sh) ─────────────
MODEL="${MODEL:-llama3.3}"

# ── 1. Install zeroclaw binary ────────────────────────────────────────────────
section "Install zeroclaw"

if command -v zeroclaw &>/dev/null; then
    info "zeroclaw already installed at $(command -v zeroclaw)"
else
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

    if [ -f "$REPO_ROOT/scripts/install.sh" ]; then
        info "Running install.sh ..."
        bash "$REPO_ROOT/scripts/install.sh"
    elif command -v cargo &>/dev/null; then
        info "Building from source with cargo ..."
        (cd "$REPO_ROOT" && cargo build --release 2>&1)
        INSTALL_DIR="${HOME}/.local/bin"
        mkdir -p "$INSTALL_DIR"
        cp "$REPO_ROOT/target/release/zeroclaw" "$INSTALL_DIR/zeroclaw"
        chmod +x "$INSTALL_DIR/zeroclaw"
        info "Installed to $INSTALL_DIR/zeroclaw"
        if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
            export PATH="$INSTALL_DIR:$PATH"
            note "Added $INSTALL_DIR to PATH for this session."
            note "Add this to your shell profile to make it permanent:"
            note "  export PATH=\"\$HOME/.local/bin:\$PATH\""
        fi
    else
        echo "ERROR: zeroclaw not found and neither install.sh nor cargo is available."
        echo "Install Rust from https://rustup.rs then re-run this script."
        exit 1
    fi
fi

# ── 2. Install Ollama ─────────────────────────────────────────────────────────
section "Install Ollama"

if command -v ollama &>/dev/null; then
    info "Ollama already installed at $(command -v ollama)"
else
    info "Installing Ollama ..."
    curl -fsSL https://ollama.com/install.sh | sh
    info "Ollama installed."
fi

# Start Ollama server in background if not already running
if ! curl -sf http://localhost:11434/api/tags &>/dev/null; then
    info "Starting Ollama server ..."
    ollama serve &>/dev/null &
    OLLAMA_PID=$!
    # Wait up to 10 seconds for it to become ready
    for i in $(seq 1 10); do
        sleep 1
        if curl -sf http://localhost:11434/api/tags &>/dev/null; then
            break
        fi
        if [ "$i" -eq 10 ]; then
            echo "ERROR: Ollama did not start within 10 seconds."
            exit 1
        fi
    done
    info "Ollama server running (pid $OLLAMA_PID)."
else
    info "Ollama server already running."
fi

# ── 3. Pull model ─────────────────────────────────────────────────────────────
section "Pull model: $MODEL"

EXISTING=$(ollama list 2>/dev/null | awk 'NR>1 {print $1}' || true)
if echo "$EXISTING" | grep -q "^${MODEL}"; then
    info "Model '$MODEL' already present — skipping pull."
else
    info "Pulling '$MODEL' (this may take a few minutes) ..."
    ollama pull "$MODEL"
    info "Model '$MODEL' ready."
fi

# ── 4. Create config directory ────────────────────────────────────────────────
section "Config directory"

CONFIG_DIR="${ZEROCLAW_CONFIG_DIR:-$HOME/.zeroclaw}"
mkdir -p "$CONFIG_DIR"
info "Config directory: $CONFIG_DIR"

# ── 5. Write offline config.toml ──────────────────────────────────────────────
section "Config file"

CONFIG_FILE="$CONFIG_DIR/config.toml"

if [ -f "$CONFIG_FILE" ]; then
    note "Config already exists at $CONFIG_FILE — skipping write."
    note "Delete it and re-run to regenerate, or edit it manually."
else
    cat > "$CONFIG_FILE" << TOML
# ~/.zeroclaw/config.toml
# Generated by scripts/setup-offline.sh
# Fully offline, zero-cost, maximum-capability ZeroClaw configuration.
#
# Runs entirely on your local machine via Ollama.
# No API key, no internet connection, no spend required.
#
# Change the model to any model you have pulled with 'ollama pull <name>'.

provider    = "ollama"
model       = "${MODEL}"
temperature = 0.7

# ── Agent ─────────────────────────────────────────────────────────────────────
[agent]
max_tool_iterations  = 100     # default 10  → raised to maximum
max_history_messages = 1000    # default 50  → raised to maximum
parallel_tools       = true    # default false → enabled for speed

# ── Ollama local fallback chain ───────────────────────────────────────────────
# Lists locally-pulled models in order of preference.
# Add more with: ollama pull <model>
[reliability]
provider_retries    = 3
provider_backoff_ms = 200
fallback_providers  = ["ollama", "lmstudio", "llamacpp"]

[reliability.model_fallbacks]
"${MODEL}" = [
  "${MODEL}",
  "qwen2.5-coder",   # great for code tasks
  "mistral",         # fast general purpose
  "phi4",            # very fast, small footprint
  "llama3.2",        # lightweight fallback
]

# ── Memory & response cache ───────────────────────────────────────────────────
[memory]
backend                     = "sqlite"
response_cache_enabled      = true    # cache local model responses → instant repeats
response_cache_ttl_minutes  = 1440    # 24-hour cache window
response_cache_max_entries  = 100000  # large LRU cache
snapshot_enabled            = true    # export core memories to MEMORY_SNAPSHOT.md
snapshot_on_hygiene         = true    # refresh snapshot on each hygiene pass
auto_save                   = true    # auto-save user messages to memory
hygiene_enabled             = true    # clean up stale entries automatically
conversation_retention_days = 365     # keep conversation history for 1 year

# ── Tool: web search (disabled — offline mode) ────────────────────────────────
[web_search]
enabled = false

# ── Tool: HTTP requests (local network only) ──────────────────────────────────
[http_request]
enabled           = true
max_response_size = 10000000  # 10 MB
timeout_secs      = 60

# ── Tool: browser automation ──────────────────────────────────────────────────
[browser]
enabled = true
backend = "agent_browser"

# ── Multimodal (images) ───────────────────────────────────────────────────────
[multimodal]
max_images         = 16    # maximum supported
max_image_size_mb  = 20    # maximum supported
allow_remote_fetch = false # offline — no remote image fetching

# ── Autonomy ──────────────────────────────────────────────────────────────────
[autonomy]
level                  = "full"
workspace_only         = false
max_actions_per_hour   = 100
max_cost_per_day_cents = 0     # local inference is always free

# ── Runtime ───────────────────────────────────────────────────────────────────
[runtime]
reasoning_enabled = true    # enable chain-of-thought when model supports it

# ── Scheduler ─────────────────────────────────────────────────────────────────
[scheduler]
enabled        = true
max_tasks      = 1024
max_concurrent = 32

# ── Cron ──────────────────────────────────────────────────────────────────────
[cron]
enabled         = true
max_run_history = 1000

# ── Heartbeat ─────────────────────────────────────────────────────────────────
[heartbeat]
enabled          = true
interval_minutes = 15

# ── Cost tracking (always zero for local inference) ───────────────────────────
[cost]
enabled           = true
daily_limit_usd   = 0.00
monthly_limit_usd = 0.00

# ── Skills ────────────────────────────────────────────────────────────────────
[skills]
open_skills_enabled   = true
prompt_injection_mode = "full"
TOML

    info "Config written to $CONFIG_FILE"
fi

# ── 6. Model menu ─────────────────────────────────────────────────────────────
section "Available local models"

echo ""
printf "  %-28s  %-10s  %s\n" "MODEL NAME" "SIZE" "BEST FOR"
printf "  %-28s  %-10s  %s\n" "----------" "----" "--------"
printf "  %-28s  %-10s  %s\n" "llama3.3"              "43 GB"  "General purpose (best quality)"
printf "  %-28s  %-10s  %s\n" "qwen2.5-coder:32b"     "20 GB"  "Code generation and review"
printf "  %-28s  %-10s  %s\n" "qwen2.5-coder:7b"      "4.7 GB" "Code on modest hardware"
printf "  %-28s  %-10s  %s\n" "mistral"               "4.1 GB" "Fast general purpose"
printf "  %-28s  %-10s  %s\n" "phi4"                  "9.1 GB" "Reasoning, small footprint"
printf "  %-28s  %-10s  %s\n" "deepseek-coder-v2:16b" "9.1 GB" "Advanced coding"
printf "  %-28s  %-10s  %s\n" "llama3.2:3b"           "2.0 GB" "Minimal hardware"
echo ""
note "Pull any model with:  ollama pull <model>"
note "Switch model in config:  model = \"<model>\""
note "Or override per-run:  zeroclaw agent --model mistral -m \"Hello\""

# ── 7. Smoke test ─────────────────────────────────────────────────────────────
section "Smoke test"

info "Running end-to-end test with model '$MODEL' ..."
zeroclaw agent -m "Reply with exactly the word: READY"
info "Smoke test passed."

section "Done"
info "ZeroClaw is running fully offline using Ollama."
info "Run:  zeroclaw agent -m \"Your task here\""
