#!/usr/bin/env bash
# setup-free.sh — ZeroClaw zero-cost, maximum-capability auto-setup
#
# Copy-paste and run:
#   bash scripts/setup-free.sh
#
# What this does:
#   1. Installs the zeroclaw binary if not already present
#   2. Creates ~/.zeroclaw/ config directory
#   3. Writes a maxed-out config.toml with all 10 free-tier providers
#   4. Prints signup links + export lines for every free API key
#   5. Runs a smoke test if any key is already set in the environment

set -euo pipefail

# ── Colours ───────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
    BOLD='\033[1m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'
    YELLOW='\033[1;33m'; RESET='\033[0m'
else
    BOLD=''; GREEN=''; CYAN=''; YELLOW=''; RESET=''
fi

info()    { echo -e "${GREEN}[setup]${RESET} $*"; }
section() { echo -e "\n${BOLD}${CYAN}━━  $*  ━━${RESET}"; }
note()    { echo -e "${YELLOW}[note]${RESET}  $*"; }

# ── 1. Install zeroclaw binary ────────────────────────────────────────────────
section "Install"

if command -v zeroclaw &>/dev/null; then
    info "zeroclaw already installed at $(command -v zeroclaw)"
else
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

    if [ -f "$REPO_ROOT/scripts/install.sh" ]; then
        info "Running install.sh ..."
        bash "$REPO_ROOT/scripts/install.sh"
    elif command -v cargo &>/dev/null; then
        info "Building from source with cargo ..."
        (cd "$REPO_ROOT" && cargo build --release 2>&1)
        INSTALL_DIR="${HOME}/.local/bin"
        mkdir -p "$INSTALL_DIR"
        cp "$REPO_ROOT/target/release/zeroclaw" "$INSTALL_DIR/zeroclaw"
        chmod +x "$INSTALL_DIR/zeroclaw"
        info "Installed to $INSTALL_DIR/zeroclaw"
        if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
            export PATH="$INSTALL_DIR:$PATH"
            note "Added $INSTALL_DIR to PATH for this session."
            note "Add the following to your shell profile to make it permanent:"
            note "  export PATH=\"\$HOME/.local/bin:\$PATH\""
        fi
    else
        echo "ERROR: zeroclaw not found and neither install.sh nor cargo is available."
        echo "Install Rust from https://rustup.rs then re-run this script."
        exit 1
    fi
fi

# ── 2. Create config directory ────────────────────────────────────────────────
section "Config directory"

CONFIG_DIR="${ZEROCLAW_CONFIG_DIR:-$HOME/.zeroclaw}"
mkdir -p "$CONFIG_DIR"
info "Config directory: $CONFIG_DIR"

# ── 3. Write maxed-out config.toml ───────────────────────────────────────────
section "Config file"

CONFIG_FILE="$CONFIG_DIR/config.toml"

if [ -f "$CONFIG_FILE" ]; then
    note "Config already exists at $CONFIG_FILE — skipping write."
    note "Delete it and re-run to regenerate, or edit it manually."
else
    cat > "$CONFIG_FILE" << 'TOML'
# ~/.zeroclaw/config.toml
# Generated by scripts/setup-free.sh
# Zero-cost, maximum-capability ZeroClaw configuration.
#
# Cerebras is the default provider (ultra-fast free tier).
# If Cerebras is rate-limited the agent automatically falls through the
# full chain of free providers below — no manual intervention needed.
#
# Set your chosen provider key as an environment variable, e.g.:
#   export CEREBRAS_API_KEY=your-key-here

provider    = "cerebras"
model       = "llama-3.3-70b"
temperature = 0.7

# ── Agent ─────────────────────────────────────────────────────────────────────
[agent]
max_tool_iterations  = 100     # default 10  → raised to maximum
max_history_messages = 1000    # default 50  → raised to maximum
parallel_tools       = true    # default false → enabled for speed

# ── Free-tier provider fallback chain ─────────────────────────────────────────
[reliability]
provider_retries    = 5
provider_backoff_ms = 500
fallback_providers  = [
  "sambanova",     # fast free inference
  "groq",          # generous free tier
  "hyperbolic",    # free credits
  "deepinfra",     # broad model hosting
  "featherless",   # free-tier serving
  "chutes",        # free community inference
  "novita",        # low-cost open models
  "siliconflow",   # free Qwen/DeepSeek (CN)
  "inference-net", # free-tier endpoint
]

[reliability.model_fallbacks]
"llama-3.3-70b" = [
  "llama-3.3-70b",                              # cerebras
  "Meta-Llama-3.3-70B-Instruct",                # sambanova
  "llama3-70b-8192",                            # groq
  "meta-llama/Llama-3.3-70B-Instruct",          # hyperbolic / featherless
  "meta-llama/Llama-3.3-70B-Instruct-Turbo",    # deepinfra
  "meta-llama/llama-3.3-70b-instruct",          # novita
  "deepseek-ai/DeepSeek-V3-0324",               # chutes (fallback model)
  "deepseek-ai/DeepSeek-V3",                    # siliconflow
  "meta-llama/llama-3.3-70b-instruct/fp-8",     # inference-net
]

# ── Memory & response cache ───────────────────────────────────────────────────
[memory]
backend                     = "sqlite"
response_cache_enabled      = true    # cache LLM responses → zero tokens on repeats
response_cache_ttl_minutes  = 1440    # 24-hour cache window
response_cache_max_entries  = 100000  # large LRU cache
snapshot_enabled            = true    # export core memories to MEMORY_SNAPSHOT.md
snapshot_on_hygiene         = true    # refresh snapshot on each hygiene pass
auto_save                   = true    # auto-save user messages to memory
hygiene_enabled             = true    # clean up stale entries automatically
conversation_retention_days = 365     # keep conversation history for 1 year

# ── Tool: web search ──────────────────────────────────────────────────────────
[web_search]
enabled      = true
provider     = "duckduckgo"   # free, no key required
max_results  = 10
timeout_secs = 30

# ── Tool: HTTP requests ───────────────────────────────────────────────────────
[http_request]
enabled           = true
max_response_size = 10000000  # 10 MB
timeout_secs      = 60

# ── Tool: browser automation ──────────────────────────────────────────────────
[browser]
enabled = true
backend = "agent_browser"

# ── Tool: Composio (1000+ OAuth integrations) ─────────────────────────────────
[composio]
enabled = true

# ── Multimodal (images) ───────────────────────────────────────────────────────
[multimodal]
max_images         = 16    # maximum supported
max_image_size_mb  = 20    # maximum supported
allow_remote_fetch = true  # allow fetching image URLs

# ── Autonomy ──────────────────────────────────────────────────────────────────
[autonomy]
level                  = "full"
workspace_only         = false
max_actions_per_hour   = 100
max_cost_per_day_cents = 0     # hard zero — only free providers are used

# ── Runtime ───────────────────────────────────────────────────────────────────
[runtime]
reasoning_enabled = true    # enable chain-of-thought when model supports it

# ── Scheduler ─────────────────────────────────────────────────────────────────
[scheduler]
enabled        = true
max_tasks      = 1024
max_concurrent = 32

# ── Cron ──────────────────────────────────────────────────────────────────────
[cron]
enabled         = true
max_run_history = 1000

# ── Heartbeat ─────────────────────────────────────────────────────────────────
[heartbeat]
enabled          = true
interval_minutes = 15

# ── Cost tracking (enforces $0 spend) ─────────────────────────────────────────
[cost]
enabled           = true
daily_limit_usd   = 0.00
monthly_limit_usd = 0.00

# ── Skills ────────────────────────────────────────────────────────────────────
[skills]
open_skills_enabled   = true
prompt_injection_mode = "full"
TOML

    info "Config written to $CONFIG_FILE"
fi

# ── 4. Free API key instructions ──────────────────────────────────────────────
section "Free API keys"

echo ""
echo "Sign up (all free) and set ONE or more of these env vars:"
echo ""
printf "  %-15s  %-42s  %s\n" "PROVIDER" "SIGNUP URL" "ENV VAR"
printf "  %-15s  %-42s  %s\n" "--------" "----------" "-------"
printf "  %-15s  %-42s  %s\n" "Cerebras"    "https://cloud.cerebras.ai"        "export CEREBRAS_API_KEY=..."
printf "  %-15s  %-42s  %s\n" "Groq"        "https://console.groq.com"         "export GROQ_API_KEY=..."
printf "  %-15s  %-42s  %s\n" "SambaNova"   "https://cloud.sambanova.ai"        "export SAMBANOVA_API_KEY=..."
printf "  %-15s  %-42s  %s\n" "Hyperbolic"  "https://app.hyperbolic.xyz"        "export HYPERBOLIC_API_KEY=..."
printf "  %-15s  %-42s  %s\n" "DeepInfra"   "https://deepinfra.com"             "export DEEPINFRA_API_KEY=..."
printf "  %-15s  %-42s  %s\n" "Featherless" "https://featherless.ai"            "export FEATHERLESS_API_KEY=..."
printf "  %-15s  %-42s  %s\n" "Chutes"      "https://chutes.ai"                 "export CHUTES_API_KEY=..."
printf "  %-15s  %-42s  %s\n" "Novita"      "https://novita.ai"                 "export NOVITA_API_KEY=..."
printf "  %-15s  %-42s  %s\n" "SiliconFlow" "https://siliconflow.cn"            "export SILICONFLOW_API_KEY=..."
printf "  %-15s  %-42s  %s\n" "inference.net" "https://inference.net"           "export INFERENCE_NET_API_KEY=..."
echo ""
note "Set the var, then run:  zeroclaw agent -m \"Hello\""
note "The agent auto-falls through the chain if one provider rate-limits."

# ── 5. Smoke test (runs only if a key is already set) ────────────────────────
ANY_KEY="${CEREBRAS_API_KEY:-}${GROQ_API_KEY:-}${SAMBANOVA_API_KEY:-}\
${HYPERBOLIC_API_KEY:-}${DEEPINFRA_API_KEY:-}${FEATHERLESS_API_KEY:-}\
${CHUTES_API_KEY:-}${NOVITA_API_KEY:-}${SILICONFLOW_API_KEY:-}${INFERENCE_NET_API_KEY:-}"

if [ -n "$ANY_KEY" ]; then
    section "Smoke test"
    info "Key detected — running end-to-end test..."
    zeroclaw agent -m "Reply with exactly the word: READY"
    info "Smoke test passed."
else
    section "Done"
    info "Setup complete. Set a free API key (see above) then run:"
    info "  zeroclaw agent -m \"Hello\""
fi
